version: '3'

services:
    postgres:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=botDb
            - POSTGRES_PASSWORD=admin
        expose: 
            - 5432
    bot:
        build: .
        depends_on: 
            - postgres
        volumes:
            - ./strangerchatbot:/strangerchatbot

volumes:
    postgres_data: